sudo: required
dist: trusty
language: go
go:
  - 1.8.1
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-pip
install:
  - go get ./...
  - go get -t ./...
  - pip install -U zschema
script:
  - go test -v ./...
  - python zgrab_schema.py
notifications:
  email:
  - zmap-devel@umich.edu
  slack:
    secure: C9nvJpSXSBuqfyv7z+vt+d0CQ4ZC5JklQj9iY9g1jpObDeBG13/THKxINTAAkKIjrgZHkeSVRjOSAE+pz6XbGKFBoFwsKqx9kc4rM7rZumlRalXgyTMc2nInWVcCwlQBGHTAmqPudXR4zMD8xRM9iNxpzOIb2cjOkPRAHw1cCXY=
